export const AUDIT_ACTIONS = {
  VIEW_PATIENT: "VIEW_PATIENT",
  COMPLETE_CONSULTATION: "COMPLETE_CONSULTATION",
  CREATE_PATIENT: "CREATE_PATIENT",
  UPDATE_PATIENT: "UPDATE_PATIENT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
};
